server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    #password: ${DB_PASSWORD:{cipher}a68de9b0597cdb81a077bc626aa714f834e6798e9c0aa53c26d5cefb2c525d06}
    #암호화한 값을 사용할 때는 위와 같은 형식은 사용 못함
    password: '{cipher}a68de9b0597cdb81a077bc626aa714f834e6798e9c0aa53c26d5cefb2c525d06'
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  secret: '{cipher}ffd7c2c647ea364fa946d211072f2f1a6ace5c3f902018422fd40bd2909752cc8d9e81c40bf9edd4bbc8b31aa6ff8fb443114d01d3eb69f6215fc37a2b101e5fbbc54dbd22f88630743244a70629bb8241dccb7182decafbe0c43185d593eb4bc607fc26352b3ba64fb351c47e4dba21'
  #secret: 8O2HQ13etL2BWZvYOiWsJ5uWFoLi6NBUG8divYVoCgtHVvlk3dqRksMl16toztDUeBTSIuOOPvHIrYq11G2BwQ==

AllowedOrigins: http://localhost:3000

# Logging
logging:
  level:
    root: INFO
