spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    permitted-list-patterns:    #수신된 Event의 역직렬화를 허용할 객체 지정
      - com.subride.common.event.*
#    deserialization:
#      trust-all: true
 
# Logging
logging:
  level:
    org.springframework.security: DEBUG
    com.subride.mysub.infra.in: DEBUG
    com.subride.mysub.infra.out: DEBUG
    feign:
      codec:
        logger:
          level: DEBUG
feign:
  subrecommend:
    url: ${SUBRECOMMEND_URI}
  mygroup:
    url: ${MYGRP_URI}
