server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    #password: ${DB_PASSWORD:{cipher}a68de9b0597cdb81a077bc626aa714f834e6798e9c0aa53c26d5cefb2c525d06}
    #암호화한 값을 사용할 때는 위와 같은 형식은 사용 못함
    # curl -X POST http://localhost:9001/encrypt -d "P@ssw0rd$"
    password: '{cipher}dbf7229281926da83068aee04aca0fdbc170fa0bdc476e8e9241f1f4e827ba3c'
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  #JWT secret키는 암호화하면 동작 안함
  #secret: '{cipher}0c77292c64cf9ac384d29b89d92a69f9ca8c2ce96da81d36946515f6e85cd1dcd31b86547b56ec86cbba773af5f77da1657411cb6d7d133417228abbde727a197c14f17fda2059a9bc7c7fb671b2600614caf65b55618bb4b512854df55ca844e5f1d89dd392051e1cc0a1cd0ddf16d8'
  secret: 8O2HQ13etL2BWZvYOiWsJ5uWFoLi6NBUG8divYVoCgtHVvlk3dqRksMl16toztDUeBTSIuOOPvHIrYq11G2BwQ==

AllowedOrigins: ${FRONT_HOST}

# Logging
logging:
  level:
    root: INFO

# Eureka client 설정: instanceId가 Eureka에 등록되는 주소임. StatefulSet으로 배포할 때만 동작함
eureka:
  instance:
    hostname: ${HOSTNAME}
    #instanceId: ${POD_IP}:${SERVER_PORT}
    instanceId: ${HOSTNAME}:${SERVER_PORT}
    preferIpAddress: false
    nonSecurePort: ${SERVER_PORT}
    securePort: 443
    nonSecurePortEnabled: true
    securePortEnabled: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVERS}

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, mappings, routes
