server:
  port: ${SERVER_PORT}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${DB_URL}
  config:
    import: configserver:member-service/env.yml
jwt:
  expiration-time: ${JWT_EXPIRATION_TIME}
  refresh-token-expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}

# Logging
logging:
  level:
    com.subride.member.infra.in: DEBUG
    com.subride.member.infra.out: DEBUG