server:
  port: ${SERVER_PORT:18080}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:member-service}
  datasource:
    url: ${DB_URL}
jwt:
  expiration-time: ${JWT_EXPIRATION_TIME}
  refresh-token-expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}

# Logging
logging:
  level:
    com.subride.member.infra.in: DEBUG
    com.subride.member.infra.out: DEBUG